# Generated by Django 4.2 on 2025-07-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_subscription_payment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='token'),
        ),
    ]
