# Generated by Django 4.2 on 2025-07-24 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user with this phone number already exist'}, unique=True, validators=[django.core.validators.RegexValidator('^09[0-9]\\d{9}$', 'Enter The valid phone number', 'invalid')], verbose_name='Phone number'),
        ),
    ]
