# Generated by Django 4.2 on 2025-07-24 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_join',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data of join'),
        ),
    ]
