# Generated by Django 4.2 on 2025-07-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_data_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_join',
            new_name='data_joined',
        ),
    ]
