# Generated by Django 4.2 on 2025-07-28 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 28, 19, 20, 21, 627542, tzinfo=datetime.timezone.utc), verbose_name='data of join'),
        ),
    ]
