# Generated by Django 4.2 on 2025-07-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data of join'),
        ),
    ]
