# Generated by Django 4.2 on 2025-07-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('sku', models.CharField(db_index=True, max_length=20, validators=[utils.validators.SKUValidator], verbose_name='stock keeping unit')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='expire time')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='subscriptions.package', verbose_name='package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
            },
        ),
    ]
