# Generated by Django 4.2 on 2025-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
    ]
